### ISSUE TITLE
Сделать кнопку(и) для сортировки\фильтра

### ISSUE THREAD

**Issue by Artyrm** [aeremin/comcon-beacons#9]
1) сортировка по давности получения данных от пользователя, по умолчанию включена. Чтобы старые уползали вниз. Если давность одинаковая ("только что"), то по алфавиту.
2) фильтр, отсекающий недельную давность.

Настроек пока не надо.

**Comment by Artyrm** [comment]
На кнопку можно забить, если это сложно

**Comment by aeremin** [comment]
Пока что без кнопки, потом сделаем сортировку по всем нужным вещам разом.
